source 'https://github.com/CocoaPods/Specs.git'

target 'Dismissy', :exclusive => true do
  pod "Dismissy", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Dismissy", :path => "../"
  pod 'KIF'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCHamcrest'
  pod 'OCMock'
  pod 'PivotalCoreKit/UIKit/SpecHelper/Extensions'

end
